esphome:
  name: esphome-web-e5cd38
  friendly_name: Bathroom Clock Controls
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  # encryption:
    # key: 

ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# captive_portal:

time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"
    # on_time:
      # - seconds: 0
        # minutes: /1 # Update every minute
        # then:
          # - component.update: my_display

packages:
  remote_package_shorthand: github://SpicyLimes/ESP32-2432S028R-CYD-Files/YAML-Configs/ESP-Screen-Remote-v1a-Package.yaml@main
