esphome:
  name: esphome-web-e5cd38
  friendly_name: Bathroom Clock Controls
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:

ota:
- platform: esphome

time:
  - platform: homeassistant
    id: ha_time
    timezone: "America/Chicago"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  on_connect:
    then:
      - light.turn_on:
          id: led
          red: 100%
          green: 100%
          blue: 100%
          brightness: 100%
  on_disconnect:
    then:
      - light.turn_on:
          id: led
          red: 100%
          green: 0%
          blue: 100%
          brightness: 100%

web_server:
  port: 80
  version: 3

packages:
  remote_package_files:
    url: https://github.com/SpicyLimes/ESP32-2432S028R-CYD-Files
    files: YAML-Configs/ESP-Screen-Remote-v1a-Package.yaml
    ref: main
    refresh: 5min
